[env:atoms3r]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Unified@^0.2.2
  bblanchon/ArduinoJson@^6.21.5
  https://github.com/tzapu/WiFiManager.git
  WebServer

board_build.partitions = default_8MB.csv
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -I../shared
